Version = 0
Id = "00000000-0000-0000-0000-000000000000"
Name = "simple"
PropertiesSchema = "schema_properties.json"
HashType = "sha2-256"

[Properties]
  description = "a bogus test holochain"
  language = "en"

[BasedOn]

[Zomes]
  [Zomes.jsZome]
    Name = "jsZome"
    Description = "this is a javascript test zome"
    Code = "zome_jsZome.js"
    NucleusType = "js"
    [Zomes.jsZome.CodeHash]
    [Zomes.jsZome.Entries]
      [Zomes.jsZome.Entries.myOdds]
        Name = "myOdds"
        DataFormat = "js"
        Schema = ""
        [Zomes.jsZome.Entries.myOdds.SchemaHash]
  [Zomes.lispZome]
    Name = "lispZome"
    Description = "this is a zygomas test zome"
    Code = "zome_lispZome.zy"
    NucleusType = "zygo"
    [Zomes.lispZome.CodeHash]
    [Zomes.lispZome.Entries]
      [Zomes.lispZome.Entries.evens]
        Name = "evens"
        DataFormat = "zygo"
        Schema = ""
        [Zomes.lispZome.Entries.evens.SchemaHash]
      [Zomes.lispZome.Entries.primes]
        Name = "primes"
        DataFormat = "zygo"
        Schema = ""
         [Zomes.lispZome.Entries.primes.SchemaHash]
      [Zomes.lispZome.Entries.profiles]
        Name = "profiles"
        DataFormat = "JSON"
        Schema = "schema_profile.json"
        [Zomes.lispZome.Entries.profiles.SchemaHash]

